// Generated by Robert M. Lefkowitz <code@liberally.net> in 2024
// from a file containing the following notice:

/*
  Copyright (c) 2012 The NetBSD Foundation, Inc.
  All rights reserved.
 
  This code is derived from software contributed to The NetBSD Foundation
  by Jukka Ruohonen.
 
  Redistribution and use in source and binary forms, with or without
  modification, are permitted provided that the following conditions
  are met:
  1. Redistributions of source code must retain the above copyright
     notice, this list of conditions and the following disclaimer.
  2. Redistributions in binary form must reproduce the above copyright
     notice, this list of conditions and the following disclaimer in the
     documentation and/or other materials provided with the distribution.
 
  THIS SOFTWARE IS PROVIDED BY THE NETBSD FOUNDATION, INC. AND CONTRIBUTORS
  ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
  TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
  PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION OR CONTRIBUTORS
  BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
  POSSIBILITY OF SUCH DAMAGE.
*/

import ShellTesting

@Suite() class catTest : ShellTest  {
  
  let cmd = "cat"
  let suiteBundle = "text_cmds_catTest"

  @Test func align() async throws {
    let x = try fileContents("d_align.out")
    let res = try inFile("d_align.in")
    try await run(output: x, args: "-be", res)
  }
  
  @Test func b_output() async throws {
    let x = try fileContents("d_b_output.out")
    let inp = try inFile("d_b_output.in")
    try await run(output: x, args: "-b", inp)
  }

  @Test func se_output() async throws {
    let x = try fileContents("d_se_output.out")
    let inp = try inFile("d_se_output.in")
    try await run(output: x, args: "-se", inp)
  }

  @Test func s_output() async throws {
    let x = try fileContents("d_s_output.out")
    let inp = try inFile("d_s_output.in")
    try await run(output: x, args: "-s", inp)
  }

  @Test func e_output() async throws {
    let x = try fileContents("d_se_output.out")
    let inp = try inFile("d_se_output.in")
    try await run(output: x, args: "-e", inp)
  }

  @Test func vt_output() async throws {
    let x = try fileContents("d_vt_output.out")
    let inp = try inFile("d_vt_output.in")
    try await run(output: x, args: "-vt", inp
//                  , env: ["LC_ALL":"en_US:CLEM", "LANG":"en_US:CLEM"]
                  // Fails without this from command line, but works in XCode
                  , env: ["LC_ALL":"", "LANG":""]
                   )
  }
  
}

