
// Generated by Robert "r0ml" Lefkowitz <code@liberally.net> in 2024
// from a file containing the following notice:

/*
  Copyright (c) 2022-2023 Klara Systems
 
  Redistribution and use in source and binary forms, with or without
  modification, are permitted provided that the following conditions
  are met:
  1. Redistributions of source code must retain the above copyright
     notice, this list of conditions and the following disclaimer.
  2. Redistributions in binary form must reproduce the above copyright
     notice, this list of conditions and the following disclaimer in the
     documentation and/or other materials provided with the distribution.
 
  THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
  ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
  ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
  FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
  DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
  OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
  HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
  OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
  SUCH DAMAGE.
 */

import ShellTesting

@Suite(.serialized) class splitTest : ShellTest {
  let cmd = "split"
  let suiteBundle = "splitTest"

  let MAXBSIZE = 256 * 4096

  @Test func bytes1() async throws {
    try await run(withStdin: "aaaabb\ncccc\n", status: 0, args: "-b", "4", "-", "split-")
    let fs = try ["aa", "ab", "ac"].map { try tmpfile("split-\($0)") }
    defer { rm(fs) }
    let os = try fs.map { try $0.readAsString() }
    #expect( "aaaa" == os[0] )
    #expect( "bb\nc" == os[1] )
    #expect( "ccc\n" == os[2] )
  }
  
  @Test func bytes2() async throws {
    let pieces = [
      String(repeating: "a", count: MAXBSIZE+12),
      String(repeating: "b", count: MAXBSIZE+12),
      String(repeating: "c", count: 12),
      ]
    
    try await run(withStdin: pieces.joined(), status: 0, args: "-b", String(MAXBSIZE+12), "-", "split-")

    let fs = try ["aa", "ab", "ac"].map { try tmpfile("split-\($0)")}
    let os = try fs.map { try $0.readAsString() }
    defer { rm(fs) }
    #expect( pieces[0] == os[0] )
    #expect( pieces[1] == os[1] )
    #expect( pieces[2] == os[2] )
  }

  @Test func chunks() async throws {
    let i = String(repeating: "a", count: 4096) +
    String(repeating: "b", count: 4096) +
    String(repeating: "c", count: 4104)
    
    // The -n option can't work on stdin, so I need a file input
    let i1 = try tmpfile("foo", i)
    try await run(args: "-n", "3", i1, "split-")

//    let po = try await p.run(i)
    let fs = try ["aa", "ab", "ac"].map { try tmpfile("split-\($0)")}
    let os = try fs.map { try $0.readAsString() }
    defer { rm(fs) }

    #expect( os[0] == String(repeating: "a", count: 4096) + String(repeating: "b", count: 2))
    #expect( os[1] == String(repeating: "b", count: 4094) + String(repeating: "c", count: 4))
    #expect( os[2] == String(repeating: "c", count: 4100))
  }

  
  @Test func sensible_lines1() async throws {
    let pieces = [
      "The quick brown fox\n",
      "jumps over\n",
      "the lazy dog\n",
    ]
    
    try await run(withStdin: pieces.joined(), status: 0, args: "-l", "1", "-", "split-")
    let fs = try ["aa", "ab", "ac"].map { try tmpfile("split-\($0)") }
    let os = try fs.map { try $0.readAsString() }
    defer { rm(fs) }
    #expect( pieces[0] == os[0] )
    #expect( pieces[1] == os[1] )
    #expect( pieces[2] == os[2] )
  }
  
  @Test func sensible_lines2() async throws {
    let pieces = [
      "The quick brown fox\n",
      "jumps over\n",
      "the lazy dog\n",
    ]
    
    try await run(withStdin: pieces.joined(), status: 0, args: "-l", "2", "-", "split-")
    let f0 = try tmpfile("split-aa")
    let f1 = try tmpfile("split-ab")
    defer { rm(f0, f1) }

    let o0 = try f0.readAsString()
    let o1 = try f1.readAsString()
    #expect( o0 == pieces[0]+pieces[1])
    #expect( o1 == pieces[2])
  }

  @Test func long_lines() async throws {
    let pieces = [
      String(repeating: "a", count: MAXBSIZE) + "\n",
      String(repeating: "b", count: MAXBSIZE) +
      String(repeating: "c", count: MAXBSIZE) + "\n",
      String(repeating: "d", count: 1024)+"\n"
    ]
    try await run(withStdin: pieces.joined(), status: 0, args: "-l", "1", "-", "split-")
    let fs = try ["aa", "ab", "ac"].map { try tmpfile("split-\($0)") }
    let os = try fs.map { try $0.readAsString() }
    defer { rm(fs) }
    #expect( pieces[0] == os[0] )
    #expect( pieces[1] == os[1] )
    #expect( pieces[2] == os[2] )
  }

  @Test func numeric_suffix() async throws {
    let pieces = [
        "The quick brown fox\n",
        "jumps over\n",
        "the lazy dog\n",
        ]
    try await run(withStdin: pieces.joined(), status: 0, args: "-d", "-l", "1", "-", "split-")
    for i in 0..<pieces.count {
      let j = cFormat("%02d", i)
      let u = try tmpfile("split-\(j)")
      defer { rm(u) }
      let o1 = try u.readAsString()
      #expect( o1 == pieces[i])
    }

  }

  @Test func larger_suffix_length() async throws {
    let pieces = (0...11).map { String(repeating: "a", count: $0)+"\n" }
    try await run(withStdin: pieces.joined(), status: 0, args: "-a", "3", "-d", "-l", "1", "-", "split-")
    for i in 0...11 {
      let j = cFormat("%03d", i)
      let u = try tmpfile("split-\(j)")
      defer { rm(u) }
      let o1 = try u.readAsString()
      #expect( o1 == pieces[i] )
    }
  }

  @Test func pattern() async throws {
    let i1 = """
cat:
  aa: true
  ab: true
  ac: true

"""
    let i2 = """
dog:
  ba: true
  bb: true
  bc: true

"""
    
    try await run(withStdin: i1+i2, status: 0, args: "-p", "^[^[:space:]]+:", "-", "split-")
    let f0 = try tmpfile("split-aa")
    let f1 = try tmpfile("split-ab")
    defer { rm(f0, f1) }
    let o0 = try f0.readAsString()
    let o1 = try f1.readAsString()
    #expect( i1 == o0 )
    #expect( i2 == o1 )
  }

  @Test func noautoextend() async throws {
    let m = 26*26
    let i = ((1...m).map { String($0)+"\n"}).joined()
    try await run(withStdin: i, status: 0, args: "-a2", "-l1")
    let f0 = try tmpfile("xzz")
    let o1 = try f0.readAsString()
    #expect( (String(m)+"\n") == o1 )
    let az = "abcdefghijklmnopqrstuvwxyz"
    let a2z = az.flatMap {a in az.map {b in "x"+String(a)+String(b) }}
    try rm( a2z.map { try tmpfile($0) } )
  }

  @Test func continue_test() async throws {
    let i = "hello\n"
    try await run(withStdin: i, status: 0)
    let f1 = try tmpfile("xaa")
    defer { rm(f1) }
    let o1 = try f1.readAsString()
    #expect( i == o1)

      let o2f = try tmpfile("xab")
    defer { rm(o2f) }
      #expect( o2f.exists )

    try await run(withStdin: i, status: 0, args: "-c")
    let o2 = try o2f.readAsString()
      #expect( i == o2 )
  }

  @Test func undocumented_kludge() async throws {
    let i = ((1...5000).map { String($0)+"\n" }).joined()
    try await run(withStdin: i, status: 0, args: "-1000")
    let f1 = try tmpfile("xae")
    defer { rm(f1) }
    let o1 = try f1.readAsString()
    let i2 = ((4001...5000).map { String($0)+"\n" }).joined()
    #expect( i2 == o1 )

    try rm(["xaa", "xab", "xac", "xad", "xae"].map { try tmpfile($0) } )

    try await run(withStdin: i, status: 0, args: "-d1000")
    let f2 = try tmpfile("x04")
    let o2 = try f2.readAsString()
    #expect( i2 == o2)
    try rm(["x00", "x01", "x02", "x03", "x04"].map { try tmpfile($0) } )

  }

  @Test(arguments: [
    (-5, -5), (-15, -5), (-5, -15), (-15, -15)
  ]) func duplicate_linecount(_ x : Int, _ y : Int) async throws {
    try await run(status: 64, args: String(x), String(y), "/dev/null")
  }
  
}
