
// Generated by Robert "r0ml" Lefkowitz <code@liberally.net> in 2024
// from a file containing the following notice:

import ShellTesting

@Suite("jq") class jqTest : ShellTest {
  let cmd = "jq"
  let suiteBundle = "text_cmds_jqTest"

  @Test("Not yet implemented") func placeHolder() async throws {
    Issue.record("Not implemented yet")
  }

}
