
// Generated by Robert "r0ml" Lefkowitz <code@liberally.net> in 2024
// from a file containing the following notice:

/*
  $FreeBSD$
*/

import Testing
import TestSupport
import Foundation

@Suite(.serialized) class colTest : ShellTest {

  let cmd = "col"
  let suite = "colTest"

  @Test("testing just newlines", arguments: ["nl", "nl2"]) func nl(_ arg : String) async throws {
    let i = try fileContents("\(arg).in")
    try await run(withStdin: i, output: arg == "nl3" ? "a\n\nb\n\n" : "a\nb\n" )
  }
  
  @Test("testing reverse line feed") func rlf() async throws {
    let i2 = try fileContents("rlf.in")
    try await run(withStdin: i2, output: "a b\n")
    
    let i3 = try fileContents("rlf2.in")
    try await run(withStdin: i3, output: "a\tb\n")
   
    let i4 = try fileContents("rlf2.in")
    try await run(withStdin: i4, output: "a       b\n",  args: "-x")

    let i5 = try fileContents("rlf3.in")
    try await run(withStdin: i5, output: " b\na\n", args: "-x")
  }

  @Test("testing half line feed") func hlf() async throws {
    let i = try fileContents("hlf.in")
    try await run(withStdin: i, output: "a f\naf\n")

    let res2 = "a f\u{1b}9\r f\u{1b}9\ra\n"
    try await run(withStdin: i, output: res2, args: "-f")

    let i3 = try fileContents("hlf2.in")
    try await run(withStdin: i3, output: "a\n f\n")

    let i4 = try fileContents("hlf2.in")
    let res4 = "a\u{1b}9\r f\n\u{1b}9"
    try await run(withStdin: i4, output: res4, args: "-f")
  }

}
