
// Generated by Robert "r0ml" Lefkowitz <code@liberally.net> in 2024
// from a file containing the following notice:

/*
  $FreeBSD$
*/

import ShellTesting

@Suite(.serialized) class colTest : ShellTest {
  
  let cmd = "col"
  let suiteBundle = "text_cmds_colTest"
  
  @Test("testing just newlines", arguments: ["nl", "nl2"]) func nl(_ arg : String) async throws {
    let i = try fileContents("\(arg).in")
    try await run(withStdin: i, output: arg == "nl3" ? "a\n\nb\n\n" : "a\nb\n" )
  }
  
  @Test("testing reverse line feed", .serialized, arguments: [
    ("rlf.in", "a b\n", []),
    ("rlf2.in", "a\tb\n", []),
    ("rlf2.in",  "a       b\n", ["-x"]),
    ("rlf3.in", " b\na\n", ["-x"]),
  ]) func rlf(_ inf : String, _ outp: String, _ args : [String]) async throws {
    let i2 = try fileContents(inf)
    try await run(withStdin: i2, output: outp, args: args)
  }
  
  @Test("testing half line feed", arguments: [
    ("hlf.in", "a f\naf\n"),
    ("hlf2.in", "a\n f\n"),
  ]) func hlf(_ inf : String, _ outp: String) async throws {
    let i = try fileContents(inf)
    try await run(withStdin: i, output: outp)
  }
  
  @Test("testing half line feed 2", arguments: [
    ("hlf.in", "a f\u{1b}9\r f\u{1b}9\ra\n"),
    ("hlf2.in", "a\u{1b}9\r f\n\u{1b}9"),
  ]) func hlf2(_ inf : String, _ outp: String) async throws {
    let i = try fileContents(inf)
    try await run(withStdin: i, output: outp, args: "-f")
  }
}
