// Generated by Robert M. Lefkowitz <code@liberally.net> in 2024 using ChatGPT
// from a file containing the following notice:

/*
 * Copyright (c) 1980, 1987, 1992, 1993
 *  The Regents of the University of California.  All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. Neither the name of the University nor the names of its contributors
 *    may be used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

import CMigration

extension FileDescriptor {
  func readLine() -> String? {
    var line = ""
    while let char = try? self.readUpToCount(1) {
      let string = String(decoding: char, as: UTF8.self)
      if string.isEmpty { break }
      if string == "\n" {
        line += string
        break
      }
      line += string
    }
    return line.isEmpty ? nil : line
  }
}

@main final class head : ShellCommand {
  
  func head(_ file: FileDescriptor, lines: Int) {
    var count = lines
    while count > 0, let line = file.readLine() {
      print(line, terminator: "")
      count -= 1
    }
  }
  
  func headBytes(_ file: FileDescriptor, bytes: Int) throws {
    var remainingBytes = bytes
    let bufferSize = 4096
  //  var buffer = Data(repeating: 0, count: bufferSize)
    
    while remainingBytes > 0 {
      let bytesToRead = min(bufferSize, remainingBytes)
      let data = try file.readUpToCount(bytesToRead)
      guard !data.isEmpty else { break }
      remainingBytes -= data.count
      try FileDescriptor.standardOutput.write(data)
    }
  }
  
  func obsolete(_ args: inout [String]) {
    for (index, arg) in args.enumerated() {
      guard arg.starts(with: "-"), arg.dropFirst().allSatisfy({ $0.isNumber }) else { continue }
      args[index] = "-n" + String(arg.dropFirst())
    }
  }
  
  var usage : String = "usage: head [-n lines | -c bytes] [file ...]"
  
  
  // Main program
  struct CommandOptions {
    var args = CommandLine.arguments
    var lineCount: Int? = nil
    var byteCount: Int? = nil
  }
  
  var options : CommandOptions!
  
  func parseOptions() throws(CmdErr) -> CommandOptions {
    var opts = CommandOptions()
    
    let oo : [LongOption] = [
      .init("bytes", .required_argument),
      .init("lines", .required_argument),
    ]
    
    let go = BSDGetopt_long("c:n:", oo)
    
    // FIXME: put this back
    //               obsolete(&args)
    
    while let (k, v) = try go.getopt_long() {
      switch k {
        case "n", "lines":
          if let value = Int(v), value > 0 {
            opts.lineCount = value
          } else {
            throw CmdErr(1, "illegal line count -- \(v)")
          }
        case "c", "bytes":
          if let value = Int(v), value > 0 {
            opts.byteCount = value
          } else {
            throw CmdErr(1, "illegal byte count -- \(v)")
          }
        default: throw CmdErr(1)
      }
    }
    
    if opts.lineCount == nil, opts.byteCount == nil {
      opts.lineCount = 10
    }
    
    opts.args = go.remaining
    
    
    if let lineCount = options.lineCount, let byteCount = options.byteCount {
      throw CmdErr(1, "Cannot combine line and byte counts")
    }
    return opts
  }
  
  func runCommand() throws(CmdErr) {
    let useStandardInput = options.args.isEmpty
    if useStandardInput {
      if let lineCount = options.lineCount {
        head(FileDescriptor.standardInput, lines: lineCount)
      } else if let byteCount = options.byteCount {
        try? headBytes(FileDescriptor.standardInput, bytes: byteCount)
      }
    } else {
      var se = FileDescriptor.standardError
      for file in options.args {
//        let u = URL(filePath: file)
        var fileHandle : FileDescriptor
        do {
          fileHandle = try FileDescriptor(forReading: file)
        } catch( let e) {
          print("Cannot open file: \(file) \(e))", to: &se)
          continue
        }
        
        if options.args.count > 1 {
          print("\n==> \(file) <==")
        }
        
        if let lineCount = options.lineCount {
          head(fileHandle, lines: lineCount)
        } else if let byteCount = options.byteCount {
          try? headBytes(fileHandle, bytes: byteCount)
        }
        try? fileHandle.close()
      }
    }
  }
}
