
// Generated by Robert "r0ml" Lefkowitz <code@liberally.net> in 2024
// from a file containing the following notice:

import Testing

struct sedTest {

  @Test func placeHolder() async throws {
      // Not yet implemented.
    #expect(false)
  }

}
