
// Generated by Robert "r0ml" Lefkowitz <code@liberally.net> in 2024
// from a file containing the following notice:

/*
  Copyright 2017 Shivansh
  All rights reserved.

  Redistribution and use in source and binary forms, with or without
  modification, are permitted provided that the following conditions
  are met:
  1. Redistributions of source code must retain the above copyright
    notice, this list of conditions and the following disclaimer.
  2. Redistributions in binary form must reproduce the above copyright
    notice, this list of conditions and the following disclaimer in the
    documentation and/or other materials provided with the distribution.

  THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
  ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
  ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
  FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
  DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
  OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
  HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
  OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
  SUCH DAMAGE.

  $FreeBSD$
 */
import Testing
import TestSupport
import Foundation

let orig = ProcessInfo.processInfo.environment["TEST_ORIGINAL"] != nil

@Suite(.serialized) class foldTest {
  
  let cl : AnyClass? =  orig ? nil : foldTest.self
  let ex = orig ? "/usr/bin/fold" : "fold"

  @Test("Verify the usage of option 'b'") func b_flag() async throws {

    let (r, j, _) = try captureStdoutLaunch(cl, ex, ["-b"])
    #expect(r == 0 && j!.isEmpty)
  }
  
  @Test("Verify the usage of option 's'") func s_flag() async throws {
    let (r, j, _) = try captureStdoutLaunch(cl, ex, ["-s"])
    // Not yet implemented.
    #expect(r == 0 && j!.isEmpty)
  }

  @Test("Verify that an invalid usage with a supported option produces a valid error message") func invalid_usage() async throws {
    let (r, j, e) = try captureStdoutLaunch(cl, ex, ["-w"])
    let ee = ex + ": option requires an argument -- w\nusage: fold [-bs] [-w width] [file ...]\n"
    #expect(r != 0 && e == ee )
  }

  @Test("Verify that fold(1) executes successfully and silently when invoked without any arguments") func no_arguments() async throws {
    let (r, j, e) = try captureStdoutLaunch(cl, ex, [])
    #expect(r == 0 && j!.isEmpty)
  }


  
  
}
