
// Generated by Robert "r0ml" Lefkowitz <code@liberally.net> in 2024
// from a file containing the following notice:

import Testing

struct jqTest {

  @Test(.disabled("Not yet implemented")) func placeHolder() async throws {
    Issue.record("Not implemented yet")
  }

}
