// Generated by Robert "r0ml" Lefkowitz <code@liberally.net> in 2025

import Testing
import TestSupport

@Suite(.serialized) class bintransTest : ShellTest {
  let cmd = "bintrans"
  let suite = "bintransTest"
 
  @Test func encode_qp() async throws {
    let t = try inFile("textqpdec")
    let u = try fileContents("textqpenc")
    try await run(output: u, args: "qp", t)
  }
  
  @Test(.serialized, arguments: [
    ("=", "="),
    ("=\ra", "=\r\na"),
    ("=\r\na", "a"),
    ("This is a line", "This is a line"),
    ("This= is a line", "This= is a line"),
    ("This=2 is a line", "This=2 is a line"),
    ("This=23 is a line", "This# is a line"),
    ("This=3D is a line", "This= is a line"),
    ("This_ is a line", "This_ is a line"),
  ]) func decode_qp(_ inp : String, _ outp : String) async throws {
    let t = try tmpfile("test", inp)
    try await run(output: outp, args: "qp", "-u", t)
    rm(t)
  }

  @Test func decode_qp_f() async throws {
    let t = try inFile("textqpenc")
    let u = try fileContents("textqpdec")
    try await run(output: u, args: "qp", "-u", t)
  }
}
