// Generated by Robert "r0ml" Lefkowitz <code@liberally.net> in 2024
// from a file containing the following notice:

import ShellTesting

struct regressTest : ShellTest {
  let cmd = "bintrans"
  let suiteBundle = "text_cmds_bintransTest"

    @Test func traditional() async throws {
      let res = try fileContents("regress.traditional.out")
      let inp = try geturl("regress.in").readAllBytes()
      try await run(withStdin: inp, output: res, args: "uuencode", "regress.in")
    }


  @Test func base64() async throws {
    let res = try fileContents("regress.base64.out")
    let inp = try geturl("regress.in").readAllBytes()
    try await run(withStdin: inp, output: res, args: "uuencode", "-m", "regress.in")
  }
  
  @Test func decode_traditional() async throws {
    let res = try geturl("regress.in").readAllBytes()
    let inp = try fileContents("regress.traditional.in")
    try await run(withStdin: inp, output: res, args: "uudecode", "-p")
  }

  @Test func decode_base64() async throws {
    let res = try geturl("regress.in").readAllBytes()
    let inp = try fileContents("regress.base64.in")
    try await run(withStdin: inp, output: res, args: "uudecode", "-p")
  }

  @Test func t153276() async throws {
//    let res = try fileData(suiteBundle, "regress.153276.out")
    let inp = try fileContents("regress.153276.in")
    try await run(withStdin: inp, status: 0,
                  error: /character out of range:/,
                  args: "uudecode", "-o", "/dev/null")
  }


}
